### ISSUE TITLE
设置根目录报错 The resource file_id cannot be found. file_id:pan

### ISSUE THREAD

**Issue by Y4er** [Xhofe/alist#106]
```yaml
ali_drive:
  api_url: https://api.aliyundrive.com/v2
  max_files_count: 50
  drives:
  - refresh_token: xxx
    root_folder: pan
    name: drive0
    password: ""
    hide: false
```

root_folder 设置为pan，然后阿里云盘中根目录下有一个pan的文件夹，rebuild报错`The resource file_id cannot be found. file_id:pan`

**Comment by Y4er** [comment]
设置为root时，进入pan文件夹的url为http://xx.com/drive0/pan，设置为pan之后rebuild就会报错

**Comment by Xhofe** [comment]
> 设置为root时，进入pan文件夹的url为http://xx.com/drive0/pan ，设置为pan之后rebuild就会报错

教程中有写哈
https://nn.ci/archives/alist.html#toc_16

如何设置根目录？
修改配置文件中的ali_drive.root_folder 为想要设置的文件夹的file_id即可。文件夹的file_id是什么？根目录就是root，其他目录为点进文件夹之后的url中folder/后面那一串

**Comment by Y4er** [comment]
不起作用，如下这是我的阿里云盘结构，根目录下有一个pan文件夹

![image](https://user-images.githubusercontent.com/40487319/117236929-5dde3500-ae5c-11eb-8cdf-c6e348ccc073.png)


```
ali_drive:
  api_url: https://api.aliyundrive.com/v2
  max_files_count: 50
  drives:
  - refresh_token: aaa
    root_folder: root
    name: drive0
    password: ""
    hide: false
```

当root修改为pan还是会报错The resource file_id cannot be found. file_id:pan
