### ISSUE TITLE
新的配置,不用配置以下吗

### ISSUE THREAD

**Issue by jing5460** [Xhofe/alist#12]
site_url: https://alist.nn.ci #网站地址，前后端分离时必须正确填写
  backend_url: https://alist.nn.ci #后端地址，用于文件直链复制，必填！！

**Comment by Xhofe** [comment]
backend_url去掉了，site_url放在了server中，直接默认'*'就好。

**Comment by jing5460** [comment]
现在出现这个错误是什么原因

**Comment by Xhofe** [comment]
> 现在出现这个错误是什么原因: The origin is not in the site_url list, please configure it
> 还是不行,还是会报错
> https://jing5460.coding.net/p/picgo/d/img/git/raw/master/20210112212206.png

```yaml
server:
  port: "5244"
  search: false
  static: dist
  site_url: '*'
```
这样也不行吗
