### ISSUE TITLE
README文件中对于带有链接标题的渲染问题

### ISSUE THREAD

**Issue by suyin-long** [Xhofe/alist#185]
### Alist Version / Alist 版本

v2.0.0

### Describe the bug / 问题描述

在README文件中如果标题中带有链接，渲染显示的效果不会显示它是个链接（文字颜色为蓝色），仅仅显示它是个标题，如下图：
![1](https://user-images.githubusercontent.com/49554285/144533653-e5834810-50d1-4478-8210-71ffb7108c0a.png)
而对于非标题的链接则渲染显示正常，如下图：
![2](https://user-images.githubusercontent.com/49554285/144533214-780d8947-0384-4145-a8be-694b366f5bda.png)

### Reproduction / 复现链接

https://suyin.shop/Tools/PC/%E8%A3%85%E6%9C%BA%E5%BF%85%E5%A4%87/Windows%20%E6%BF%80%E6%B4%BB

**Comment by Xhofe** [comment]
等上游解决，可以先自行在自定义样式中加入
```css
#md-editor-rt a[href^="http"]{
  color: #539bf5;
}
#md-editor-rt a[href^="http"]:hover{
  text-decoration:underline;
}
```
