### ISSUE TITLE
Docker版本

### ISSUE THREAD

**Issue by bebestmaple** [Xhofe/alist#54]
请问能否开发Docker版本，方便部署

**Comment by naicfeng** [comment]
`Dockerfile`
```
FROM alpine:3.12.4

# Replace alpine apk source
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/g' /etc/apk/repositories

# Add glibc package
COPY ./glibc-2.31-r0.apk /lib/

# Add glibc key
RUN wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub

# Install glibc
RUN apk add /lib/glibc-2.31-r0.apk

ARG UNAME=alist
ARG UID=1003
ARG GID=1003

RUN addgroup -g $GID $UNAME
RUN adduser $UNAME -D -G $UNAME -u $UID -s /bin/sh

USER $UNAME

# Set workdir
WORKDIR /alist/alist

# Add start shell
COPY launch.sh /tmp/

# Add cloudreve binary file and default config file
COPY conf.yml /alist/files/

# Entrypoint
CMD sh /tmp/launch.sh

```


`launch.sh`
```
#!/bin/sh
# If config file not exist, copy default config file to there
if [[ ! -f /alist/alist/conf.yml ]]; then
  cp /alist/files/* /alist/alist/
fi

# Run
./alist
```


`docker-compose.yml`
```
version: '3'
services:
  cloudreve:
    image: xxx/alist
    container_name: alist
    volumes:
      - ./work_dir:/alist/alist
    ports:
      - "127.0.0.1:5244:5244"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    restart: unless-stopped
    networks:
      - docker-net

networks:
  docker-net:
    external: true
```

也可以不要launch，用它是方便集成其他服务
